const DATA={"radius":5,"cells":[[-5,0],[-5,1],[-5,2],[-5,3],[-5,4],[-5,5],[-4,-1],[-4,0],[-4,1],[-4,2],[-4,3],[-4,4],[-4,5],[-3,-2],[-3,-1],[-3,0],[-3,1],[-3,2],[-3,3],[-3,4],[-3,5],[-2,-3],[-2,-2],[-2,-1],[-2,0],[-2,1],[-2,2],[-2,3],[-2,4],[-2,5],[-1,-4],[-1,-3],[-1,-2],[-1,-1],[-1,0],[-1,1],[-1,2],[-1,3],[-1,4],[-1,5],[0,-5],[0,-4],[0,-3],[0,-2],[0,-1],[0,0],[0,1],[0,2],[0,3],[0,4],[0,5],[1,-5],[1,-4],[1,-3],[1,-2],[1,-1],[1,0],[1,1],[1,2],[1,3],[1,4],[2,-5],[2,-4],[2,-3],[2,-2],[2,-1],[2,0],[2,1],[2,2],[2,3],[3,-5],[3,-4],[3,-3],[3,-2],[3,-1],[3,0],[3,1],[3,2],[4,-5],[4,-4],[4,-3],[4,-2],[4,-1],[4,0],[4,1],[5,-5],[5,-4],[5,-3],[5,-2],[5,-1],[5,0]],"directions":[["Forward",0,-1],["Forstar",1,-1],["Aftstar",1,0],["Aft",0,1],["Aftport",-1,1],["Forport",-1,0]]},R=DATA.radius,SQ3=Math.sqrt(3),WALL_H=2.4,EYE_H=1,HFOV=100*Math.PI/180,NEAR=.05;
const dirs=DATA.directions,cellSet=new Set(DATA.cells.map(c=>`${c[0]},${c[1]}`));let viewer={q:0,r:R,heading:0};
const valid=(q,r)=>cellSet.has(`${q},${r}`),center=(q,r)=>({x:SQ3*(q+r/2),y:1.5*r});
function vertex(c,k){const a=(30+60*k)*Math.PI/180;return{x:c.x+Math.cos(a),y:c.y+Math.sin(a)}}
const byDir=Array.from({length:6},()=>[]);for(const[q,r]of DATA.cells){const c=center(q,r);for(let d=0;d<6;d++){const[,dq,dr]=dirs[d];if(!valid(q+dq,r+dr))byDir[d].push(vertex(c,(d+3)%6),vertex(c,(d+4)%6))}}
function farthest(P){let z=[P[0],P[1]],bd=-1;for(let i=0;i<P.length;i++)for(let j=i+1;j<P.length;j++){let dx=P[i].x-P[j].x,dy=P[i].y-P[j].y,d=dx*dx+dy*dy;if(d>bd){bd=d;z=[P[i],P[j]]}}return z}
const walls=byDir.map((p,d)=>{let[a,b]=farthest(p);return{a,b,d,src:`assets/wall-${dirs[d][0].toLowerCase()}.svg`}}),root=document.getElementById('walls');walls.forEach(w=>{let e=document.createElement('div');e.className='wall';let i=document.createElement('img');i.src=w.src;e.appendChild(i);root.appendChild(e)});
function cam(p,z){const v=center(viewer.q,viewer.r),dx=p.x-v.x,dy=p.y-v.y,a=-viewer.heading*Math.PI/180;return{x:dx*Math.cos(a)-dy*Math.sin(a),y:z-EYE_H,z:-(dx*Math.sin(a)+dy*Math.cos(a))}}
function clip(poly){let out=[];for(let i=0;i<poly.length;i++){let A=poly[i],B=poly[(i+1)%poly.length],ai=A.z>=NEAR,bi=B.z>=NEAR;if(ai)out.push(A);if(ai!==bi){let t=(NEAR-A.z)/(B.z-A.z);out.push({x:A.x+t*(B.x-A.x),y:A.y+t*(B.y-A.y),z:NEAR})}}return out}
function proj(p,W,H){let f=(W/2)/Math.tan(HFOV/2);return{x:W/2+p.x*f/p.z,y:H/2-p.y*f/p.z,d:p.z}}
function place(el,Q){let xs=Q.map(p=>p.x),ys=Q.map(p=>p.y),x0=Math.min(...xs),x1=Math.max(...xs),y0=Math.min(...ys),y1=Math.max(...ys),w=Math.max(1,x1-x0),h=Math.max(1,y1-y0);el.style.left=x0+'px';el.style.top=y0+'px';el.style.width=w+'px';el.style.height=h+'px';el.style.clipPath=`polygon(${Q.map(p=>`${(p.x-x0)/w*100}% ${(p.y-y0)/h*100}%`).join(',')})`}
function render(){let W=innerWidth,H=innerHeight,E=[...root.children];walls.forEach((w,i)=>{let poly=clip([cam(w.a,WALL_H),cam(w.b,WALL_H),cam(w.b,0),cam(w.a,0)]),el=E[i];if(poly.length<3){el.style.display='none';return}let q=poly.map(p=>proj(p,W,H));el.style.display='block';place(el,q);let dist=poly.reduce((s,p)=>s+p.z,0)/poly.length;el.style.zIndex=String(Math.max(1,10000-Math.round(dist*500)))});hud.textContent=`POSITION ${viewer.q},${viewer.r} · HEADING ${Math.round(viewer.heading)}° · FOV 100°`}
function hi(){return((Math.round(viewer.heading/60)%6)+6)%6}function move(o){let d=(hi()+o+6)%6,[,dq,dr]=dirs[d],q=viewer.q+dq,r=viewer.r+dr;if(valid(q,r)){viewer.q=q;viewer.r=r;render()}else location.href='ouch.html'}function turn(d){viewer.heading=(viewer.heading+d+360)%360;render()}
fwd.onclick=()=>move(0);back.onclick=()=>move(3);left.onclick=()=>move(-1);right.onclick=()=>move(1);tl1.onclick=()=>turn(-60);tr1.onclick=()=>turn(60);bl2.onclick=()=>turn(-120);br2.onclick=()=>turn(120);addEventListener('keydown',e=>{if(e.key==='ArrowUp')move(0);if(e.key==='ArrowDown')move(3);if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1)});addEventListener('resize',render);render();